/*
    THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
    if you want to view the source, please visit the github repository of this plugin
    */
    
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DateHeaderInserter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DateHeaderInserter = class extends import_obsidian.Plugin {
  // This function is called when the plugin is loaded.
  async onload() {
    this.addCommand({
      id: "insert-date-header",
      name: "Insert date as H2 heading",
      // The editorCallback is triggered when the command is executed.
      editorCallback: (editor, view) => {
        const now = new Date();
        const year = now.getFullYear();
        const month = String(now.getMonth() + 1).padStart(2, "0");
        const dayOfMonth = String(now.getDate()).padStart(2, "0");
        const daysOfWeek = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
        const dayOfWeek = daysOfWeek[now.getDay()];
        const hours = String(now.getHours()).padStart(2, "0");
        const minutes = String(now.getMinutes()).padStart(2, "0");
        const fullDateString = `${year}-${month}-${dayOfMonth} ${hours}:${minutes} ${dayOfWeek}`;
        const newHeader = `## ${fullDateString}`;
        editor.replaceSelection(newHeader);
      }
    });
  }
  // This function is called when the plugin is disabled.
  onunload() {
  }
};
